#!/usr/bin/env python3
"""
setup.py — ESP32 Automotive Dashboard project setup script

Generates:
  1. ui/assets/vehicle_top.png  — car silhouette PNG (from SVG via PIL render)
  2. ui/assets/vehicle_top.c    — LVGL C image array
  3. ui/ui.h                    — dashboard widget declarations
  4. ui/ui.c                    — full LVGL widget tree (SLS-style export)
  5. src/User_Setup.h           — TFT_eSPI pin configuration
  6. dashboard.spj              — SquareLine Studio project file (open in SLS)

Run: python3 setup.py
"""

import os
import sys
import struct
import json
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT   = Path(__file__).parent
SRC    = ROOT / "src"
UI     = ROOT / "ui"
ASSETS = UI / "assets"

UI.mkdir(exist_ok=True)
ASSETS.mkdir(exist_ok=True)

# ── Display config ─────────────────────────────────────────────────────────────
W, H = 1024, 600  # ESP32-P4-Function-EV-Board: 7" 1024x600 MIPI-DSI

# ── Colors (RGB565 hex for LVGL) ───────────────────────────────────────────────
COL_BG      = 0x0841   # #0a0a0a  (near-black)
COL_ACCENT  = 0x071A   # #00e5cc  (teal)
COL_WHITE   = 0xFFFF
COL_GREY    = 0xAD55   # #aaaaaa
COL_RED     = 0xF800   # #ff0000
COL_PANEL   = 0x18C3   # #111111 panel bg

# ─────────────────────────────────────────────────────────────────────────────
# 1. GENERATE VEHICLE PNG
# ─────────────────────────────────────────────────────────────────────────────

def generate_vehicle_png():
    """Draw a top-down car silhouette using PIL and save as PNG."""
    try:
        from PIL import Image, ImageDraw, ImageFilter
    except ImportError:
        print("[!] Pillow not installed — run: pip3 install Pillow")
        sys.exit(1)

    IW, IH = 80, 160
    img = Image.new("RGBA", (IW, IH), (0, 0, 0, 0))
    d   = ImageDraw.Draw(img)

    # Body (rounded rect, silver gradient approximated with fill)
    body_poly = [
        (28, 8), (32, 6), (48, 6), (52, 8),
        (64, 14), (68, 30), (70, 50),
        (70, 115), (68, 130), (64, 148),
        (52, 155), (28, 155),
        (16, 148), (12, 130), (10, 115),
        (10, 50), (12, 30), (16, 14),
    ]
    d.polygon(body_poly, fill=(180, 180, 180, 255), outline=(80, 80, 80, 255))

    # Cabin roof area (darker)
    cabin_poly = [
        (22, 52), (58, 52), (58, 108), (22, 108)
    ]
    d.polygon(cabin_poly, fill=(140, 140, 140, 255), outline=(70, 70, 70, 200))

    # Roof highlight
    d.rectangle([28, 56, 52, 104], fill=(200, 200, 200, 180))

    # Front windshield (dark glass)
    wind_f = [(26, 32), (54, 32), (52, 52), (28, 52)]
    d.polygon(wind_f, fill=(30, 50, 70, 220))

    # Rear windshield
    wind_r = [(28, 108), (52, 108), (54, 128), (26, 128)]
    d.polygon(wind_r, fill=(30, 50, 70, 180))

    # Front headlights
    d.ellipse([13, 14, 26, 22], fill=(200, 220, 255, 230))
    d.ellipse([54, 14, 67, 22], fill=(200, 220, 255, 230))

    # Rear taillights
    d.ellipse([13, 138, 26, 148], fill=(255, 40, 40, 220))
    d.ellipse([54, 138, 67, 148], fill=(255, 40, 40, 220))

    # Side mirrors
    d.polygon([(10, 44), (6, 46), (6, 52), (10, 52)], fill=(140, 140, 140, 220))
    d.polygon([(70, 44), (74, 46), (74, 52), (70, 52)], fill=(140, 140, 140, 220))

    # Door crease line
    d.line([(10, 80), (70, 80)], fill=(100, 100, 100, 160), width=1)

    # Slight blur for smooth look
    img = img.filter(ImageFilter.SMOOTH)

    out = ASSETS / "vehicle_top.png"
    img.save(out, "PNG")
    print(f"[1/6] Vehicle PNG generated: {out}  ({IW}×{IH})")
    return IW, IH


# ─────────────────────────────────────────────────────────────────────────────
# 2. GENERATE LVGL C IMAGE ARRAY
# ─────────────────────────────────────────────────────────────────────────────

def generate_lvgl_image_c(img_w, img_h):
    """Convert vehicle_top.png to LVGL RGB565 + alpha C array."""
    try:
        from PIL import Image
    except ImportError:
        print("[!] Pillow not installed")
        sys.exit(1)

    png_path = ASSETS / "vehicle_top.png"
    img = Image.open(png_path).convert("RGBA")

    pixels = list(img.getdata())
    pixel_data = []
    for r, g, b, a in pixels:
        # LVGL v9 ARGB8888: B, G, R, A (little-endian layout)
        pixel_data.append(b)
        pixel_data.append(g)
        pixel_data.append(r)
        pixel_data.append(a)

    hex_rows = []
    for i in range(0, len(pixel_data), 16):
        chunk = pixel_data[i:i+16]
        hex_rows.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")

    c_content = f"""\
/**
 * vehicle_top.c — LVGL image descriptor for top-down car silhouette
 * Generated by setup.py — do not edit manually
 * Format: LVGL v9 LV_COLOR_FORMAT_ARGB8888 (BGRA, 4 bytes/pixel)
 */

#ifdef __has_include
  #if __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif
#ifndef LV_ATTRIBUTE_IMG_VEHICLE_TOP
#define LV_ATTRIBUTE_IMG_VEHICLE_TOP
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_VEHICLE_TOP uint8_t vehicle_top_map[] = {{
{chr(10).join(hex_rows)}
}};

/* LVGL v9 image descriptor */
const lv_image_dsc_t vehicle_top = {{
    .header = {{
        .magic      = LV_IMAGE_HEADER_MAGIC,
        .cf         = LV_COLOR_FORMAT_ARGB8888,
        .w          = {img_w},
        .h          = {img_h},
        .stride     = {img_w * 4},
    }},
    .data_size  = {img_w * img_h * 4},
    .data       = vehicle_top_map,
}};
"""
    out = ASSETS / "vehicle_top.c"
    out.write_text(c_content)
    print(f"[2/6] LVGL image C array generated: {out}")


# ─────────────────────────────────────────────────────────────────────────────
# 3. GENERATE ui.h
# ─────────────────────────────────────────────────────────────────────────────

def generate_ui_h():
    content = """\
/**
 * ui.h — Dashboard widget declarations
 * Generated by setup.py — mirrors SquareLine Studio export format
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// Vehicle silhouette image — defined in assets/vehicle_top.c (LVGL v9 format)
extern const lv_image_dsc_t vehicle_top;

// ── Screen ──────────────────────────────────────────────────────────────────
extern lv_obj_t *ui_Screen1;

// ── Speedometer (left panel) ─────────────────────────────────────────────────
extern lv_obj_t *ui_SpeedPanel;
extern lv_obj_t *ui_SpeedBgArc;        // full grey background ring
extern lv_obj_t *ui_SpeedArc;          // teal value arc (0–220)
extern lv_obj_t *ui_SpeedLabel;        // large speed number
extern lv_obj_t *ui_SpeedUnitLabel;    // "mph"
extern lv_obj_t *ui_FuelRangeLabel;    // "⛽ 200 mi"

// ── Tachometer (right panel) ─────────────────────────────────────────────────
extern lv_obj_t *ui_RpmPanel;
extern lv_obj_t *ui_RpmBgArc;          // full grey background ring
extern lv_obj_t *ui_RpmArc;            // teal value arc (0–70 internal, = 0–7000 RPM)
extern lv_obj_t *ui_RpmRedArc;         // static red arc (70–80 = 7000–8000 redline)
extern lv_obj_t *ui_GearLabel;         // current gear number
extern lv_obj_t *ui_DriveModeLabel;    // "Sport", "Dynamic" etc
extern lv_obj_t *ui_CoolantLabel;      // "🌡 195°F"

// ── Center panel ─────────────────────────────────────────────────────────────
extern lv_obj_t *ui_CenterPanel;
extern lv_obj_t *ui_VehicleImg;        // top-down car silhouette
extern lv_obj_t *ui_TireFrontLeft;     // "41\\npsi"
extern lv_obj_t *ui_TireFrontRight;
extern lv_obj_t *ui_TireRearLeft;
extern lv_obj_t *ui_TireRearRight;
extern lv_obj_t *ui_OdometerLabel;     // "1250 mi"

// ── Header ────────────────────────────────────────────────────────────────────
extern lv_obj_t *ui_AmbientTempLabel;  // "72°F"
extern lv_obj_t *ui_DriveModeHeader;   // "M" (mode indicator)
extern lv_obj_t *ui_AdasIcon;          // ADAS status icon

// ── Init ─────────────────────────────────────────────────────────────────────
void ui_init(void);

#ifdef __cplusplus
}
#endif
"""
    out = UI / "ui.h"
    out.write_text(content)
    print(f"[3/6] ui.h generated: {out}")


# ─────────────────────────────────────────────────────────────────────────────
# 4. GENERATE ui.c  (full LVGL widget tree)
# ─────────────────────────────────────────────────────────────────────────────

def generate_ui_c():
    """Generate the complete LVGL C widget tree for the dashboard."""

    # Layout constants
    # Left gauge center: x=190, y=240 (radius ~180)
    # Right gauge center: x=610, y=240
    # Center panel: x=300..500

    GAUGE_R      = 210   # outer arc radius (larger for 1024x600)
    ARC_W        = 14    # arc stroke width
    GAUGE_DIAM   = GAUGE_R * 2

    # 1024x600: speedo cx=230, tacho cx=794, center panel 430..594
    SPD_CX, SPD_CY = 230, 310
    RPM_CX, RPM_CY = 794, 310

    content = f"""\
/**
 * ui.c — Dashboard LVGL widget tree
 * Generated by setup.py — mirrors SquareLine Studio export format
 *
 * Layout (800×480):
 *   [  Speedometer  |  Tire/Vehicle  |  Tachometer  ]
 *   Left panel cx=190  Center 300-500  Right panel cx=610
 */

#include "ui.h"
#include <stdio.h>

// ── Widget handles ────────────────────────────────────────────────────────────
lv_obj_t *ui_Screen1;
lv_obj_t *ui_SpeedPanel;
lv_obj_t *ui_SpeedBgArc;
lv_obj_t *ui_SpeedArc;
lv_obj_t *ui_SpeedLabel;
lv_obj_t *ui_SpeedUnitLabel;
lv_obj_t *ui_FuelRangeLabel;

lv_obj_t *ui_RpmPanel;
lv_obj_t *ui_RpmBgArc;
lv_obj_t *ui_RpmArc;
lv_obj_t *ui_RpmRedArc;
lv_obj_t *ui_GearLabel;
lv_obj_t *ui_DriveModeLabel;
lv_obj_t *ui_CoolantLabel;

lv_obj_t *ui_CenterPanel;
lv_obj_t *ui_VehicleImg;
lv_obj_t *ui_TireFrontLeft;
lv_obj_t *ui_TireFrontRight;
lv_obj_t *ui_TireRearLeft;
lv_obj_t *ui_TireRearRight;
lv_obj_t *ui_OdometerLabel;

lv_obj_t *ui_AmbientTempLabel;
lv_obj_t *ui_DriveModeHeader;
lv_obj_t *ui_AdasIcon;

// ── Helpers ───────────────────────────────────────────────────────────────────

static lv_obj_t * make_gauge_bg(lv_obj_t *parent, int cx, int cy, int diam)
{{
    lv_obj_t *arc = lv_arc_create(parent);
    lv_obj_set_size(arc, diam, diam);
    lv_obj_set_pos(arc, cx - diam/2, cy - diam/2);

    // Full 270° background ring
    lv_arc_set_bg_angles(arc, 135, 45);     // 270° sweep, gap at bottom
    lv_arc_set_value(arc, 0);
    lv_arc_set_range(arc, 0, 100);

    // Bg arc style: dark grey ring
    lv_obj_set_style_arc_color(arc, lv_color_hex(0x2a2a2a), LV_PART_MAIN);
    lv_obj_set_style_arc_width(arc, {ARC_W + 2}, LV_PART_MAIN);

    // Indicator arc: invisible (we use a separate arc for the value)
    lv_obj_set_style_arc_opa(arc, LV_OPA_TRANSP, LV_PART_INDICATOR);
    lv_obj_set_style_bg_opa(arc, LV_OPA_TRANSP, LV_PART_KNOB);
    lv_obj_clear_flag(arc, LV_OBJ_FLAG_CLICKABLE);
    return arc;
}}

static lv_obj_t * make_value_arc(lv_obj_t *parent, int cx, int cy, int diam,
                                  lv_color_t color, int range_max)
{{
    lv_obj_t *arc = lv_arc_create(parent);
    lv_obj_set_size(arc, diam, diam);
    lv_obj_set_pos(arc, cx - diam/2, cy - diam/2);

    lv_arc_set_bg_angles(arc, 135, 45);
    lv_arc_set_range(arc, 0, range_max);
    lv_arc_set_value(arc, 0);

    // Hide bg, show only indicator
    lv_obj_set_style_arc_opa(arc, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_arc_color(arc, color, LV_PART_INDICATOR);
    lv_obj_set_style_arc_width(arc, {ARC_W}, LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(arc, true, LV_PART_INDICATOR);
    lv_obj_set_style_bg_opa(arc, LV_OPA_TRANSP, LV_PART_KNOB);
    lv_obj_clear_flag(arc, LV_OBJ_FLAG_CLICKABLE);
    return arc;
}}

static lv_obj_t * make_label(lv_obj_t *parent, const char *text,
                              const lv_font_t *font, lv_color_t color,
                              int x, int y, lv_text_align_t align)
{{
    lv_obj_t *lbl = lv_label_create(parent);
    lv_label_set_text(lbl, text);
    lv_obj_set_style_text_font(lbl, font, LV_PART_MAIN);
    lv_obj_set_style_text_color(lbl, color, LV_PART_MAIN);
    lv_obj_set_style_text_align(lbl, align, LV_PART_MAIN);
    lv_obj_set_pos(lbl, x, y);
    return lbl;
}}

// ── Speedometer ───────────────────────────────────────────────────────────────

static void build_speedometer(lv_obj_t *screen)
{{
    const int cx = {SPD_CX}, cy = {SPD_CY};
    const int diam = {GAUGE_DIAM};

    // Transparent panel container
    ui_SpeedPanel = lv_obj_create(screen);
    lv_obj_set_size(ui_SpeedPanel, 380, {H});
    lv_obj_set_pos(ui_SpeedPanel, 0, 0);
    lv_obj_set_style_bg_opa(ui_SpeedPanel, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_SpeedPanel, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_clear_flag(ui_SpeedPanel, LV_OBJ_FLAG_SCROLLABLE);

    // Background arc (dark grey ring)
    ui_SpeedBgArc = make_gauge_bg(ui_SpeedPanel, cx, cy, diam);

    // Tick marks (scale: 0 20 40 60 80 100 120 140 160 180 200 220)
    // Rendered as small static arcs at each major division — skipped for now,
    // add via lv_meter or custom draw callback if needed

    // Value arc (teal)
    ui_SpeedArc = make_value_arc(ui_SpeedPanel, cx, cy, diam,
                                  lv_color_hex(0x00e5cc), 220);

    // Speed number — large center label
    ui_SpeedLabel = make_label(ui_SpeedPanel, "0",
        &lv_font_montserrat_48, lv_color_hex(0xFFFFFF),
        cx - 48, cy - 40, LV_TEXT_ALIGN_CENTER);
    lv_obj_set_width(ui_SpeedLabel, 96);

    // "mph" sub-label
    ui_SpeedUnitLabel = make_label(ui_SpeedPanel, "mph",
        &lv_font_montserrat_16, lv_color_hex(0xAAAAAA),
        cx - 24, cy + 16, LV_TEXT_ALIGN_CENTER);

    // Fuel range bottom label
    ui_FuelRangeLabel = make_label(ui_SpeedPanel, "200 mi",
        &lv_font_montserrat_14, lv_color_hex(0xCCCCCC),
        cx - 40, cy + {GAUGE_R - 20}, LV_TEXT_ALIGN_CENTER);
    lv_obj_set_width(ui_FuelRangeLabel, 80);
}}

// ── Tachometer ────────────────────────────────────────────────────────────────

static void build_tachometer(lv_obj_t *screen)
{{
    const int cx = {RPM_CX}, cy = {RPM_CY};
    const int diam = {GAUGE_DIAM};

    ui_RpmPanel = lv_obj_create(screen);
    lv_obj_set_size(ui_RpmPanel, 380, {H});
    lv_obj_set_pos(ui_RpmPanel, 420, 0);
    lv_obj_set_style_bg_opa(ui_RpmPanel, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_RpmPanel, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_clear_flag(ui_RpmPanel, LV_OBJ_FLAG_SCROLLABLE);

    // Background arc
    ui_RpmBgArc = make_gauge_bg(ui_RpmPanel, cx - 420, cy, diam);

    // Main value arc (teal, 0–70 maps to 0–7000 RPM)
    ui_RpmArc = make_value_arc(ui_RpmPanel, cx - 420, cy, diam,
                                lv_color_hex(0x00e5cc), 70);

    // Static redline arc (always visible, 70–80 = 7000–8000)
    ui_RpmRedArc = lv_arc_create(ui_RpmPanel);
    lv_obj_set_size(ui_RpmRedArc, diam, diam);
    lv_obj_set_pos(ui_RpmRedArc, (cx - 420) - diam/2, cy - diam/2);
    {{
        // Calculate angles for 70–80 on 270° sweep starting at 135°
        // total range = 80 units over 270°, so 1 unit = 3.375°
        // 70 units = 135 + 70*3.375 = 135 + 236.25 = 371.25 → 11.25°
        // 80 units = end = 45° (wrap)
        // So redline: start_angle=11, end_angle=45
        lv_arc_set_bg_angles(ui_RpmRedArc, 11, 45);
        lv_arc_set_value(ui_RpmRedArc, 100);
        lv_arc_set_range(ui_RpmRedArc, 0, 100);
        lv_obj_set_style_arc_opa(ui_RpmRedArc, LV_OPA_TRANSP, LV_PART_MAIN);
        lv_obj_set_style_arc_color(ui_RpmRedArc, lv_color_hex(0xFF2222), LV_PART_INDICATOR);
        lv_obj_set_style_arc_width(ui_RpmRedArc, {ARC_W}, LV_PART_INDICATOR);
        lv_obj_set_style_bg_opa(ui_RpmRedArc, LV_OPA_TRANSP, LV_PART_KNOB);
        lv_obj_clear_flag(ui_RpmRedArc, LV_OBJ_FLAG_CLICKABLE);
    }}

    // Gear number
    ui_GearLabel = make_label(ui_RpmPanel, "0",
        &lv_font_montserrat_48, lv_color_hex(0xFFFFFF),
        (cx - 420) - 36, cy - 44, LV_TEXT_ALIGN_CENTER);
    lv_obj_set_width(ui_GearLabel, 72);

    // Drive mode label
    ui_DriveModeLabel = make_label(ui_RpmPanel, "Sport",
        &lv_font_montserrat_16, lv_color_hex(0xAAAAAA),
        (cx - 420) - 30, cy + 10, LV_TEXT_ALIGN_CENTER);
    lv_obj_set_width(ui_DriveModeLabel, 60);

    // Coolant temp
    ui_CoolantLabel = make_label(ui_RpmPanel, "195°F",
        &lv_font_montserrat_14, lv_color_hex(0xCCCCCC),
        (cx - 420) - 36, cy + {GAUGE_R - 20}, LV_TEXT_ALIGN_CENTER);
    lv_obj_set_width(ui_CoolantLabel, 72);
}}

// ── Center panel ──────────────────────────────────────────────────────────────

static void build_center_panel(lv_obj_t *screen)
{{
    // Center panel bounds: x=430..594 (1024x600 layout)
    const int PX = 430, PW = 164;
    const int CENTER_X = PX + PW/2;  // 512

    ui_CenterPanel = lv_obj_create(screen);
    lv_obj_set_size(ui_CenterPanel, PW, {H});
    lv_obj_set_pos(ui_CenterPanel, PX, 0);
    lv_obj_set_style_bg_opa(ui_CenterPanel, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_CenterPanel, LV_OPA_TRANSP, LV_PART_MAIN);
    lv_obj_clear_flag(ui_CenterPanel, LV_OBJ_FLAG_SCROLLABLE);

    // Vehicle silhouette image (centered horizontally, vertically centered)
    ui_VehicleImg = lv_img_create(ui_CenterPanel);
    lv_img_set_src(ui_VehicleImg, &vehicle_top);
    lv_obj_align(ui_VehicleImg, LV_ALIGN_CENTER, 0, 10);

    // Tire pressure labels — positioned around the vehicle image
    // Vehicle img is 80×160, centered at (100,250) within panel
    // Front tires: top flanks
    ui_TireFrontLeft = make_label(ui_CenterPanel, "41\\npsi",
        &lv_font_montserrat_14, lv_color_hex(0xFFFFFF),
        6, 110, LV_TEXT_ALIGN_CENTER);
    lv_obj_set_width(ui_TireFrontLeft, 44);

    ui_TireFrontRight = make_label(ui_CenterPanel, "41\\npsi",
        &lv_font_montserrat_14, lv_color_hex(0xFFFFFF),
        150, 110, LV_TEXT_ALIGN_CENTER);
    lv_obj_set_width(ui_TireFrontRight, 44);

    // Rear tires: bottom flanks
    ui_TireRearLeft = make_label(ui_CenterPanel, "45\\npsi",
        &lv_font_montserrat_14, lv_color_hex(0xFFFFFF),
        6, 250, LV_TEXT_ALIGN_CENTER);
    lv_obj_set_width(ui_TireRearLeft, 44);

    ui_TireRearRight = make_label(ui_CenterPanel, "45\\npsi",
        &lv_font_montserrat_14, lv_color_hex(0xFFFFFF),
        150, 250, LV_TEXT_ALIGN_CENTER);
    lv_obj_set_width(ui_TireRearRight, 44);

    // Odometer — below vehicle
    ui_OdometerLabel = make_label(ui_CenterPanel, "1250 mi",
        &lv_font_montserrat_14, lv_color_hex(0xAAAAAA),
        50, 390, LV_TEXT_ALIGN_CENTER);
    lv_obj_set_width(ui_OdometerLabel, 100);
}}

// ── Header bar ────────────────────────────────────────────────────────────────

static void build_header(lv_obj_t *screen)
{{
    // Ambient temp — top right of center
    ui_AmbientTempLabel = make_label(screen, "72°F",
        &lv_font_montserrat_16, lv_color_hex(0xFFFFFF),
        360, 14, LV_TEXT_ALIGN_LEFT);

    // Drive mode header — next to temp
    ui_DriveModeHeader = make_label(screen, "M",
        &lv_font_montserrat_16, lv_color_hex(0xFFFFFF),
        410, 14, LV_TEXT_ALIGN_LEFT);

    // ADAS icon placeholder (real icon would be lv_img with icon asset)
    ui_AdasIcon = make_label(screen, "[ADAS]",
        &lv_font_montserrat_12, lv_color_hex(0x00e5cc),
        360, 36, LV_TEXT_ALIGN_LEFT);
}}

// ── Startup animation ─────────────────────────────────────────────────────────

static void startup_anim(void)
{{
    // Sweep speed arc from 0→220→0 on boot (1.5s)
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, ui_SpeedArc);
    lv_anim_set_values(&a, 0, 220);
    lv_anim_set_time(&a, 1200);
    lv_anim_set_playback_time(&a, 800);
    lv_anim_set_exec_cb(&a, (lv_anim_exec_xcb_t)lv_arc_set_value);
    lv_anim_set_path_cb(&a, lv_anim_path_ease_in_out);
    lv_anim_start(&a);

    // Sweep RPM arc
    lv_anim_t b;
    lv_anim_init(&b);
    lv_anim_set_var(&b, ui_RpmArc);
    lv_anim_set_values(&b, 0, 80);
    lv_anim_set_time(&b, 1200);
    lv_anim_set_playback_time(&b, 800);
    lv_anim_set_exec_cb(&b, (lv_anim_exec_xcb_t)lv_arc_set_value);
    lv_anim_set_path_cb(&b, lv_anim_path_ease_in_out);
    lv_anim_start(&b);
}}

// ── ui_init ───────────────────────────────────────────────────────────────────

void ui_init(void)
{{
    // Screen
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x0a0a0a), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Screen1, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);

    build_speedometer(ui_Screen1);
    build_tachometer(ui_Screen1);
    build_center_panel(ui_Screen1);
    build_header(ui_Screen1);

    lv_scr_load(ui_Screen1);

    startup_anim();
}}
"""
    out = UI / "ui.c"
    out.write_text(content)
    print(f"[4/6] ui.c generated: {out}")


# ─────────────────────────────────────────────────────────────────────────────
# 5. (skipped) TFT_eSPI User_Setup.h
# ESP32-P4 uses MIPI-DSI via BSP — TFT_eSPI is not used.
# Display init is handled by espressif/esp32_p4_function_ev_board BSP.
# ─────────────────────────────────────────────────────────────────────────────

def generate_user_setup_h():
    print("[5/6] Skipped User_Setup.h (ESP32-P4 uses MIPI-DSI BSP, not TFT_eSPI)")


# ─────────────────────────────────────────────────────────────────────────────
# 6. GENERATE SquareLine Studio .spj project file
# ─────────────────────────────────────────────────────────────────────────────

def generate_spj():
    """
    Generate a SquareLine Studio project file (.spj).
    SLS .spj is a JSON file. This gives you a pre-configured canvas
    you can open and refine in SLS without starting from scratch.
    """
    spj = {
        "version": "1.4.0",
        "name": "automotive_dashboard",
        "board": "ESP32_Arduino",
        "lvgl_version": "8.3.6",
        "display_width": W,
        "display_height": H,
        "color_depth": 16,
        "default_font": "lv_font_montserrat_16",
        "ui_export_path": "./ui",
        "libraries_export_path": "./ui",
        "project_export_root_path": ".",
        "screens": [
            {
                "name": "Screen1",
                "style": {
                    "bg_color": "#0a0a0a",
                    "bg_opa": 255
                },
                "children": [
                    # Left panel - Speedometer
                    {
                        "name": "SpeedPanel",
                        "type": "lv_obj",
                        "x": 0, "y": 0, "w": 380, "h": H,
                        "style": {"bg_opa": 0, "border_opa": 0},
                        "children": [
                            {
                                "name": "SpeedBgArc",
                                "type": "lv_arc",
                                "x": 5, "y": 30,
                                "w": 350, "h": 350,
                                "bg_start_angle": 135, "bg_end_angle": 45,
                                "range_min": 0, "range_max": 220,
                                "value": 0,
                                "arc_color_main": "#2a2a2a",
                                "arc_width_main": 14,
                                "arc_opa_indicator": 0
                            },
                            {
                                "name": "SpeedArc",
                                "type": "lv_arc",
                                "x": 5, "y": 30,
                                "w": 350, "h": 350,
                                "bg_start_angle": 135, "bg_end_angle": 45,
                                "range_min": 0, "range_max": 220,
                                "value": 0,
                                "arc_opa_main": 0,
                                "arc_color_indicator": "#00e5cc",
                                "arc_width_indicator": 12,
                                "arc_rounded_indicator": True
                            },
                            {
                                "name": "SpeedLabel",
                                "type": "lv_label",
                                "x": 142, "y": 200,
                                "w": 96,
                                "text": "0",
                                "text_font": "lv_font_montserrat_48",
                                "text_color": "#ffffff",
                                "text_align": "center"
                            },
                            {
                                "name": "SpeedUnitLabel",
                                "type": "lv_label",
                                "x": 166, "y": 256,
                                "text": "mph",
                                "text_font": "lv_font_montserrat_16",
                                "text_color": "#aaaaaa"
                            },
                            {
                                "name": "FuelRangeLabel",
                                "type": "lv_label",
                                "x": 150, "y": 360,
                                "text": "200 mi",
                                "text_font": "lv_font_montserrat_14",
                                "text_color": "#cccccc"
                            }
                        ]
                    },
                    # Center panel
                    {
                        "name": "CenterPanel",
                        "type": "lv_obj",
                        "x": 300, "y": 0, "w": 200, "h": H,
                        "style": {"bg_opa": 0, "border_opa": 0},
                        "children": [
                            {
                                "name": "VehicleImg",
                                "type": "lv_img",
                                "x": 60, "y": 80,
                                "src": "vehicle_top.png"
                            },
                            {
                                "name": "TireFrontLeft",
                                "type": "lv_label",
                                "x": 6, "y": 110,
                                "w": 44,
                                "text": "41\npsi",
                                "text_font": "lv_font_montserrat_14",
                                "text_color": "#ffffff",
                                "text_align": "center"
                            },
                            {
                                "name": "TireFrontRight",
                                "type": "lv_label",
                                "x": 150, "y": 110,
                                "w": 44,
                                "text": "41\npsi",
                                "text_font": "lv_font_montserrat_14",
                                "text_color": "#ffffff",
                                "text_align": "center"
                            },
                            {
                                "name": "TireRearLeft",
                                "type": "lv_label",
                                "x": 6, "y": 250,
                                "w": 44,
                                "text": "45\npsi",
                                "text_font": "lv_font_montserrat_14",
                                "text_color": "#ffffff",
                                "text_align": "center"
                            },
                            {
                                "name": "TireRearRight",
                                "type": "lv_label",
                                "x": 150, "y": 250,
                                "w": 44,
                                "text": "45\npsi",
                                "text_font": "lv_font_montserrat_14",
                                "text_color": "#ffffff",
                                "text_align": "center"
                            },
                            {
                                "name": "OdometerLabel",
                                "type": "lv_label",
                                "x": 50, "y": 390,
                                "w": 100,
                                "text": "1250 mi",
                                "text_font": "lv_font_montserrat_14",
                                "text_color": "#aaaaaa",
                                "text_align": "center"
                            }
                        ]
                    },
                    # Right panel - Tachometer
                    {
                        "name": "RpmPanel",
                        "type": "lv_obj",
                        "x": 420, "y": 0, "w": 380, "h": H,
                        "style": {"bg_opa": 0, "border_opa": 0},
                        "children": [
                            {
                                "name": "RpmBgArc",
                                "type": "lv_arc",
                                "x": 25, "y": 30,
                                "w": 350, "h": 350,
                                "bg_start_angle": 135, "bg_end_angle": 45,
                                "range_min": 0, "range_max": 80,
                                "value": 0,
                                "arc_color_main": "#2a2a2a",
                                "arc_width_main": 14,
                                "arc_opa_indicator": 0
                            },
                            {
                                "name": "RpmArc",
                                "type": "lv_arc",
                                "x": 25, "y": 30,
                                "w": 350, "h": 350,
                                "bg_start_angle": 135, "bg_end_angle": 45,
                                "range_min": 0, "range_max": 80,
                                "value": 0,
                                "arc_opa_main": 0,
                                "arc_color_indicator": "#00e5cc",
                                "arc_width_indicator": 12,
                                "arc_rounded_indicator": True
                            },
                            {
                                "name": "RpmRedArc",
                                "type": "lv_arc",
                                "x": 25, "y": 30,
                                "w": 350, "h": 350,
                                "bg_start_angle": 11, "bg_end_angle": 45,
                                "range_min": 0, "range_max": 100,
                                "value": 100,
                                "arc_opa_main": 0,
                                "arc_color_indicator": "#ff2222",
                                "arc_width_indicator": 12,
                                "note": "static redline 7000-8000 RPM"
                            },
                            {
                                "name": "GearLabel",
                                "type": "lv_label",
                                "x": 154, "y": 196,
                                "w": 72,
                                "text": "0",
                                "text_font": "lv_font_montserrat_48",
                                "text_color": "#ffffff",
                                "text_align": "center"
                            },
                            {
                                "name": "DriveModeLabel",
                                "type": "lv_label",
                                "x": 160, "y": 250,
                                "w": 60,
                                "text": "Sport",
                                "text_font": "lv_font_montserrat_16",
                                "text_color": "#aaaaaa",
                                "text_align": "center"
                            },
                            {
                                "name": "CoolantLabel",
                                "type": "lv_label",
                                "x": 154, "y": 360,
                                "w": 72,
                                "text": "195\u00b0F",
                                "text_font": "lv_font_montserrat_14",
                                "text_color": "#cccccc",
                                "text_align": "center"
                            }
                        ]
                    },
                    # Header
                    {
                        "name": "AmbientTempLabel",
                        "type": "lv_label",
                        "x": 360, "y": 14,
                        "text": "72\u00b0F",
                        "text_font": "lv_font_montserrat_16",
                        "text_color": "#ffffff"
                    },
                    {
                        "name": "DriveModeHeader",
                        "type": "lv_label",
                        "x": 410, "y": 14,
                        "text": "M",
                        "text_font": "lv_font_montserrat_16",
                        "text_color": "#ffffff"
                    },
                    {
                        "name": "AdasIcon",
                        "type": "lv_label",
                        "x": 360, "y": 36,
                        "text": "[ADAS]",
                        "text_font": "lv_font_montserrat_12",
                        "text_color": "#00e5cc"
                    }
                ]
            }
        ]
    }

    out = ROOT / "dashboard.spj"
    out.write_text(json.dumps(spj, indent=2))
    print(f"[6/6] SquareLine Studio project file: {out}")
    print("       → Open in SquareLine Studio to refine layout visually")


# ─────────────────────────────────────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  ESP32 Automotive Dashboard — Project Setup")
    print("=" * 60)

    img_w, img_h = generate_vehicle_png()
    generate_lvgl_image_c(img_w, img_h)
    generate_ui_h()
    generate_ui_c()
    generate_user_setup_h()
    generate_spj()

    print()
    print("=" * 60)
    print("  Done! Project structure:")
    print("=" * 60)

    for p in sorted(ROOT.rglob("*")):
        if p.is_file() and ".git" not in str(p):
            rel = p.relative_to(ROOT)
            size = p.stat().st_size
            print(f"  {str(rel):<45} {size:>8,} bytes")

    print()
    print("Next steps (ESP32-P4-Function-EV-Board):")
    print("  1. pio run                     — first build (fetches BSP components)")
    print("  2. pio run -t upload           — flash to /dev/cu.usbmodem1101")
    print("  3. pio device monitor          — serial output at 115200 baud")
    print("  4. Open dashboard.spj in SquareLine Studio (1024x600)")
    print("     to refine layout visually, then re-export to ui/")


if __name__ == "__main__":
    main()
