/**
 * ui.h — Dashboard widget declarations
 * Generated by setup.py — mirrors SquareLine Studio export format
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// Vehicle silhouette image — defined in assets/vehicle_top.c (LVGL v9 format)
extern const lv_image_dsc_t vehicle_top;

// ── Screen ──────────────────────────────────────────────────────────────────
extern lv_obj_t *ui_Screen1;

// ── Speedometer (left panel) ─────────────────────────────────────────────────
extern lv_obj_t *ui_SpeedPanel;
extern lv_obj_t *ui_SpeedBgArc;        // full grey background ring
extern lv_obj_t *ui_SpeedArc;          // teal value arc (0–220)
extern lv_obj_t *ui_SpeedLabel;        // large speed number
extern lv_obj_t *ui_SpeedUnitLabel;    // "mph"
extern lv_obj_t *ui_FuelRangeLabel;    // "⛽ 200 mi"

// ── Tachometer (right panel) ─────────────────────────────────────────────────
extern lv_obj_t *ui_RpmPanel;
extern lv_obj_t *ui_RpmBgArc;          // full grey background ring
extern lv_obj_t *ui_RpmArc;            // teal value arc (0–70 internal, = 0–7000 RPM)
extern lv_obj_t *ui_RpmRedArc;         // static red arc (70–80 = 7000–8000 redline)
extern lv_obj_t *ui_GearLabel;         // current gear number
extern lv_obj_t *ui_DriveModeLabel;    // "Sport", "Dynamic" etc
extern lv_obj_t *ui_CoolantLabel;      // "🌡 195°F"

// ── Center panel ─────────────────────────────────────────────────────────────
extern lv_obj_t *ui_CenterPanel;
extern lv_obj_t *ui_VehicleImg;        // top-down car silhouette
extern lv_obj_t *ui_TireFrontLeft;     // "41\npsi"
extern lv_obj_t *ui_TireFrontRight;
extern lv_obj_t *ui_TireRearLeft;
extern lv_obj_t *ui_TireRearRight;
extern lv_obj_t *ui_OdometerLabel;     // "1250 mi"

// ── Header ────────────────────────────────────────────────────────────────────
extern lv_obj_t *ui_AmbientTempLabel;  // "72°F"
extern lv_obj_t *ui_DriveModeHeader;   // "M" (mode indicator)
extern lv_obj_t *ui_AdasIcon;          // ADAS status icon

// ── Init ─────────────────────────────────────────────────────────────────────
void ui_init(void);

#ifdef __cplusplus
}
#endif
